os: linux
sudo: required
      
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: out/*
  skip_cleanup: true
  
services:
  - docker

script:
  - . docker.sh

post_install:
  - echo "***********************************"
  - ls out/

