name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: bash ./docker.sh
      
    - uses: actions/upload-artifact@master
      with:
        name: vscode-arm64
        path: out/
